export const siteConfig = {
  title: 'SanlyÝörelge',
  description:
    'SanlyÝörelge - bu ýaş IT hünärmenlere ýol ýörelge.',
  url: {
    twitter: '#',
    youtube: '#',
    repo: '#',
    contribute:
      '#',
    issue: '#',
  },
  keywords: [
    'SanlyÝörelge',
    'developer SanlyÝörelge',
    'developer SanlyÝörelge',
    'nädip developer bolmaly?',
    ...[
      'frontend developer',
      'backend developer',
      'sre',
      'devops',
      'android developer',
      'dba',
      'blockchain developer',
      'qa',
      'qa engineer',
      'software architect',
      'asp.net core developer',
      'react developer',
      'angular developer',
      'vue developer',
      'node.js developer',
      'javascript developer',
      'python developer',
      'go developer',
      'java developer',
      'design system',
      'software design',
      'graphql',
    ].flatMap((roadmapKeyword) => [
      `${roadmapKeyword} SanlyÝörelge`,
      `${roadmapKeyword} SanlyÝörelge 2024`,
    ]),
  ],
};
